language: c
sudo: required
services:
  - docker

env:
  global:
    - BUILD_IMAGE="vpp"
    - DOCKER_USERNAME="roadrunnr"
    - secure: "cKgn3eIbAUCWgubeySZULtOR7fjqYFc5TFIh57PfcsfzutDrqgDpyzXkCM2tJDIl2P1U3t7SIat/L+TCaevCwI4Mr2iO19HiATYa9jY29IHgcB3rANlNgWta9uzhUdZ9/7Bgvov7c2h83bLXzeHe1Eg9MNhGxRaRQvyTTR1jo9y6Shv6Hr/iGteOzT3pY416Q2QBW4FBWqcVMLqGtz6ryg72CAFcI+MPDan//Snm2vQqovCCn5vBaqVv/nnmomCF0aMAevl2jp2ZVMD8+0kTpT2zdoI3TXQG7/yb2YVPhWso6er1kQqj2IKaYK30XbzpxqK/BVIHZDPd7tHRs/tTZoWg+/iOy7v4HQKsuScJ8YF1AMB9OHaEFesBhtWAIqY4oXWHfNwUi9K1ryry4zQSRAb7mh/D2U9/nAkK+sm1bJ+Jly/wUdEXwMKyU/eO3bKO4j+h16wdbUbV2TfJ0PZnJd40FuWkfGjJWZrhnXdDOYJPHSr+Q8xRG9F4SQwR0NvUmA6qp1xyFX5ZU7M6oSbTW87Pj6p0Q+kz9npF4g8qvst8yrd+O4V84urD8415ER6B3D7+eetPb1xYRrSif6vPBwjPA0jvYBwlH2ll4REXgfgTOm6gJCdLppxhm+e0SFpxZ4z7Iv3B69XTVXsuEkL8ZMaJMklVxgVc6V8ohrNe3DU="

script:
  - docker build -t $BUILD_IMAGE -f extras/docker/Dockerfile .

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export TAG=`if [ "$TRAVIS_EVENT_TYPE" == "pull_request" ]; then echo PR-$TRAVIS_PULL_REQUEST_BRANCH ; else echo $TRAVIS_BRANCH ; fi`
  - if [ "$TAG" == "feature/gtp-up" ]; then export TAG="latest"; fi
  - docker tag $BUILD_IMAGE $BUILD_IMAGE:$TAG
  - docker push $BUILD_IMAGE:$TAG
  - echo "docker push done"
